# NumPy (Numerical Python)

Pustaka NumPy berisi array multidimensi dan struktur data matriks.

In [1]:
# Install NumPy : 
# !conda install numpy atau !pip install numpy

import numpy as np

In [8]:
np.__version__

'1.25.2'

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
a.shape

(3, 4)

In [20]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [22]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [25]:
np.arange(0, 10, 2) #start, stop, step

array([0, 2, 4, 6, 8])

### Add, Remove, Sort Array

In [28]:
arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


In [31]:
# Menambah array

np.append(arr, [1,2])

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [33]:
# Menghapus array

np.delete(arr, 1)

array([0, 2, 3, 4, 5, 6, 7])

In [36]:
# Mengurutkan array

arr2 = np.array([2, 5, 8, 9, 12, 6])
np.sort(arr2)

array([ 2,  5,  6,  8,  9, 12])

## Shape and Size

In [37]:
a = np.array([2, 5, 8, 9, 12, 6])

print("Dimensi  : ", a.ndim)
print("Size     : ", a.size)
print("Shape    : ", a.shape)

Dimensi  :  1
Size     :  6
Shape    :  (6,)


In [40]:
array = np.array([[[0, 1, 2, 3],
                   [4, 5, 6, 7]],
                  
                  [[0, 1, 2, 3],
                   [4, 5, 6, 7]],
                  
                  [[0, 1, 2, 3],
                   [4, 5, 6, 7]]])
print(array)
print("\n")
print("Dimensi  : ", array.ndim)
print("Size     : ", array.size)
print("Shape    : ", array.shape)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


Dimensi  :  3
Size     :  24
Shape    :  (3, 2, 4)


## Reshape

In [45]:
a = np.array([2, 5, 8, 9, 12, 6])

b = a.reshape(3, 2)
print("A = ", a)
print("B = ", b)

print("\nA Shape : ", a.shape)
print("B Shape : ", b.shape)

A =  [ 2  5  8  9 12  6]
B =  [[ 2  5]
 [ 8  9]
 [12  6]]

A Shape :  (6,)
B Shape :  (3, 2)


## Menambah Dimensi Array

In [46]:
x = np.array([2, 5, 8, 9, 12, 6])

y = a[np.newaxis]   # convert array 1D menjadi 2D
print("X = ", x)
print("Y = ", y)

print("\nA Shape : ", x.shape)
print("B Shape : ", y.shape)

X =  [ 2  5  8  9 12  6]
Y =  [[ 2  5  8  9 12  6]]

A Shape :  (6,)
B Shape :  (1, 6)


In [54]:
x = np.array([2, 5, 8, 9, 12, 6])

y = np.expand_dims(x, axis = 1)   # Menambahkan dimensi pada axis 1
print("X = ", x)
print("Y = ", y)

print("\nA Shape : ", x.shape)
print("B Shape : ", y.shape)

X =  [ 2  5  8  9 12  6]
Y =  [[ 2]
 [ 5]
 [ 8]
 [ 9]
 [12]
 [ 6]]

A Shape :  (6,)
B Shape :  (6, 1)


## Indexing dan Slicing

In [65]:
x = np.array([2, 5, 8, 9, 12, 6])
print("Array :", x)

# Indexing
print("Array ke-4 : ", x[4])
print("Array ke-2-4 : ", x[2:4])

# Slicing
print("\nArray < 8 : ", x[x<8])
print("Array genap : ", x % 2 == 0)
print("Array Habis dibagi 2 dan 3 : ", (x % 2 == 0) & (x % 3 == 0))

Array : [ 2  5  8  9 12  6]
Array ke-4 :  12
Array ke-2-4 :  [8 9]

Array < 8 :  [2 5 6]
Array genap :  [ True False  True False  True  True]
Array Habis dibagi 2 dan 3 :  [False False False False  True  True]


## Membuat Array dari Array yang Ada

In [72]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1 : \n", a1)
print("\nArray 2 : \n", a2)

# Membuat vertical stack
print("\nArray 1 & 2 V : \n", np.vstack([a1, a2]))

# Membuat horizontlal stack
print("\nArray 1 & 2 H : \n", np.hstack([a1, a2]))

Array 1 : 
 [[1 2 3]
 [4 5 6]]

Array 2 : 
 [[ 7  8  9]
 [10 11 12]]

Array 1 & 2 V : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array 1 & 2 H : 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [80]:
a_split = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

print("Array : \n", a_split)

# Membuat vertical split
print("\nArray split V : \n", np.vsplit(a_split, 2))

# Membuat horizontlal split
print("\nArray split H : \n", np.hsplit(a_split, 2))

Array : 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

Array split V : 
 [array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])]

Array split H : 
 [array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])]


In [83]:
aa = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array A : ", aa) 

# Membuat array baru dengan data yang sama dengan array aa
ab = aa.view()
print("\nArray B :", ab)

# Membuat deep copy dari array aa
ac = aa.copy()
print("\nArray C :", ac)

Array A :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array B : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array C : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Array Operations

In [94]:
data = np.array([1, 2])
print(data)

# Addition 
print("Penjumlahan : ", data + data)
print("Sum Array : ", data.sum())   # menjumlahkan elemen array (1 + 2 = 3)

# Subtraction
print("Pengurangan : ", data - data)

# Multiplication
print("Perkalian : ", data * data)
print("Perkalian data x 2 : ", data * 2)

# Division
print("Pembagian : ", data / data)

[1 2]
Penjumlahan :  [2 4]
Sum Array :  3
Pengurangan :  [0 0]
Perkalian :  [1 4]
Perkalian data x 2 :  [2 4]
Pembagian :  [1. 1.]


<b>Broadcasting</b> -> mekanisme yang memungkinkan NumPy untuk melakukan operasi pada array dengan bentuk berbeda. Misalnya data array [1, 2] x 2 maka kedua elemen array akan dikalikan dengan 2. dan untuk array [1, 2] x [1, 2] maka yang akan dikalikan adalah [1x1 2x2]

In [101]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array : \n", arr, "\n")
print("Max : ", arr.max())
print("Min : ", arr.min())
print("Sum : ", arr.sum())
print("Std : ", arr.std())

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Max :  12
Min :  1
Sum :  78
Std :  3.452052529534663


## Matriks Aritmatika

In [109]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 1 : \n", a_1)
print("A1 Shape : ", a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print("\nArray 2 : \n", a_2)
print("A2 Shape : ", a_2.shape)

# Perkalian 2 matriks
print("\nPerkalian : \n", np.dot(a_1, a_2))

Array 1 : 
 [[1 2 3]
 [4 5 6]]
A1 Shape :  (2, 3)

Array 2 : 
 [[ 7  8]
 [ 9 10]
 [11 12]]
A2 Shape :  (3, 2)

Perkalian : 
 [[ 58  64]
 [139 154]]


## Transposing and Reshaping

In [119]:
matriks = np.array([[7, 8], [9, 10], [11, 12]])

print("Matriks : \n", matriks)

# Transpos
print("\nTranspos : \n", matriks.T)

# Reshape
print("\nReshape : \n", matriks.reshape(1, 6))

Matriks : 
 [[ 7  8]
 [ 9 10]
 [11 12]]

Transpos : 
 [[ 7  9 11]
 [ 8 10 12]]

Reshape : 
 [[ 7  8  9 10 11 12]]
